#  使用说明
# extract-lemon-list.yml：  
# 见readme

name: extract_lemon_list
on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ main ]
    path:
      - "lemon.site"
jobs:
  read-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Read and save content
      run: |
         # Install PCRE library and pcregrep command
         # 此部分代码只需要执行一次，用于安装PCRE环境，用于执行pcregrep命令，安装以后后续运行不需要重复安装，可注释掉。
         # sudo apt-get update
         # sudo apt-get install -y libpcre3-dev
         # sudo apt-get install -y pcregrep
          
          url=$(cat lemon.site)
          echo "url=$url" >> $GITHUB_ENV
          echo "" > lemon.sub
          echo "" > lemon.list
          curl -L "$url" -o lemon.sub
          cat lemon.sub | base64 -d > lemon.list
      
          url2=$(cat lemon.site | sed 's/vrn/ch/g')
          echo "url2=$url2" >> $GITHUB_ENV
          echo "" > lemon.yaml
          curl -L "$url2" -o lemon.yaml
           
          echo "" > lemonlite.yaml
          cat lemon.yaml | perl -ne 'print unless /^proxy-group/../^$/' > lemonlite.yaml
          cat lemonlitebanner.yaml >> lemonlite.yaml
          echo "" > lemonnode.yaml
          cat lemon.yaml | perl -ne 'print unless /^proxy-group/../^$/' > lemonnode.yaml
      
          url3=$(cat lemon.site | sed 's/vrn/sg4/g')
          echo "url3=$url3" >> $GITHUB_ENV
          echo "" >lemonSurge.list
          curl -L "$url3" -o lemonSurge.list
          echo "" > lemonsg4.list          
#         cat lemonSurge.list | perl -ne 'print if /(?<=DIRECT = direct\n)(?:.+\n)*.*/' > lemonsg4.list
#         cat lemonSurge.list | pcregrep -M '(?<=DIRECT = direct\n).+?(?=\[Proxy Group\])' > lemonsg4.list
          cat lemonSurge.list | pcregrep -M '(?s)\[Proxy\].+?(?=\[Proxy Group\])' > lemonsg4.list
#         cat lemonSurge.list | perl -ne 'print if /^\[Proxy\]\n(?:.+\n)*.*(?=\[Proxy Group\])/' > lemonsg4.list
          
#        curl https://knmvc.site/N2o9/CddhK/vrn -o lemon.sub
#        cat lemon.sub | base64 -d > lemon.list
    - name: Commit changes
      run: |
        git config --local user.email "wang_zi_mo@163.com"
        git config --local user.name "fqw000"
        git add lemon.sub lemon.list lemon.yaml lemonlite.yaml lemonnode.yaml lemonsg4.list lemonSurge.list
        git commit -m "Add lemon.sub lemon.list lemon.yaml lemonlite.yaml lemonnode.yaml lemonsg4.list lemonSurge.list"
        git push
